# TODO this first dict is not needed any longer, but might come in handy

mod_dict = { # todo rename to examtype2mod or something like that
    "ARTHRO": "Sonographie", "DIFF SCHLU": "Sonographie", "HSG": "Sonographie",
    "KM SONO": "Sonographie", "KRKKDVT": "Roentgen", "KRKKOPG": "Roentgen", "MAMMA": "Roentgen",
    "NABLUT": "Szintigraphi", "NAGALLE": "Szintigraphi", "NALEBER": "Szintigraphi", "NALEER": "Szintigraphi",
    "NAMECKEL": "Szintigraphi", "NAMILZ": "Szintigraphi", "NAPAROTIS": "Szintigraphi", "NBDEXA": "Szintigraphi",
    "NBEPH": "Szintigraphi", "NB1PH": "Szintigraphi", "NB2PH": "Szintigraphi", "NB3PH": "Szintigraphi",
    "NCNAB": "CT", "NCNABB": "CT", "NCNAOB": "CT", "NCNBE": "CT", "NCNCO": "CT", "NCNHA": "CT",
    "NCNKGDEN": "CT", "NCNKGE": "CT", "NCNKGOK": "CT", "NCNKGUK": "CT", "NCNKO": "CT", "NCNKSCH": "CT",
    "NCNOBDS": "CT", "NCNOL": "CT", "NCNOR": "CT", "NCNR": "CT", "NCNRTHA": "CT", "NCNRTHAB": "CT",
    "NCNTH": "CT", "NCNTHH": "CT", "NCNTHO": "CT", "NCNTHOVPCT": "CT", "NCNUBDS": "CT", "NCNUL": "CT",
    "NCNUR": "CT", "NCNWS": "CT", "NENNM": "Szintigraphi", "NENNR": "Szintigraphi", "NENSD": "Szintigraphi",
    "NESDJOD": "Szintigraphi", "NESDMIBI": "Szintigraphi", "NESDSZJ123": "Szintigraphi",
    "NESDSZJ131": "Szintigraphi", "NESDTC": "Szintigraphi", "NESONO": "Sonographie", "NESONOP": "Sonographie",
    "NETNSJOD": "Szintigraphi", "NETNSJ123": "Szintigraphi", "NETNSMIBI": "Szintigraphi",
    "NETNSONO": "Sonographie", "NETNSTHYRS": "Szintigraphi", "NHLEUKO": "Szintigraphi",
    "NHLYMPH": "Szintigraphi", "NHSENTINEL": "Szintigraphi", "NHSENTMABD": "Szintigraphi",
    "NHSENTMAMM": "Szintigraphi", "NHSENTMELA": "Szintigraphi", "NHTHROMB": "Szintigraphi",
    "NKBELA": "Szintigraphi", "NKMPS": "Szintigraphi", "NKMPSB": "Szintigraphi", "NKMPSR": "Szintigraphi",
    "NKRNV1": "Szintigraphi", "NKRNV2": "Szintigraphi", "NLUNGE": "Szintigraphi", "NLUNGPERF": "Szintigraphi",
    "NNIBZM": "Szintigraphi", "NNIOFLUP": "Szintigraphi", "NNLIQUOR": "Szintigraphi", "NNPERF": "Szintigraphi",
    "NNPETDOPA": "Szintigraphi", "NNPETFDG": "Szintigraphi", "NNYNPET": "Szintigraphi",
    "NOCTREO": "Szintigraphi", "NODMSA5": "Szintigraphi", "NOGA": "Szintigraphi", "NOINFEKT": "Szintigraphi",
    "NOINZEV": "Szintigraphi", "NOMIBG": "Szintigraphi", "NOPETCHOL": "Szintigraphi",
    "NOPETDOPA": "Szintigraphi", "NOPETFDG": "Szintigraphi", "NOREZEPTOR": "Szintigraphi",
    "NOSPTEST": "Szintigraphi", "NPBONE": "PET/CT", "NPEXTIMP": "PET/CT", "NPHERZ": "PET/CT",
    "NPHIRN": "PET/CT", "NPHIRNAMYL": "PET/CT", "NPHIRNFET": "PET/CT", "NPOISAR": "PET/CT",
    "NPONKINF": "PET/CT", "NPOPETCHOL": "Szintigraphi", "NPOPETGADO": "Szintigraphi",
    "NPOPETGAEX": "Szintigraphi", "NPOPFPSMA": "Szintigraphi", "NPOPGAPSMA": "Szintigraphi",
    "NRECZEIT": "Szintigraphi", "NUDYN": "Szintigraphi", "NUSTAT": "Szintigraphi", "NXESZI": "Szintigraphi",
    "NXLCTABD": "CT", "NXLCTBECK": "CT", "NXLCTHA": "CT", "NXLCTOB": "CT", "NXLCTOE": "CT", "NXLCTSCH": "CT",
    "NXLCTTH": "CT", "NXLCTUE": "CT", "NXLCTWS": "CT", "RADABB": "Fluoroscopie", "RADANIER": "Fluoroscopie",
    "RADAV": "Fluoroscopie", "RADK": "Fluoroscopie", "RADKFCT": "CT", "RADNAO": "Fluoroscopie",
    "RADNIGUIDE": "Fluoroscopie", "RADOE": "Fluoroscopie", "RADTBR": "Fluoroscopie", "RADUE": "Fluoroscopie",
    "RADWLS": "Fluoroscopie", "RAEAO": "Fluoroscopie", "RAEKH": "Fluoroscopie", "RAEOE": "Fluoroscopie",
    "RAEUE": "Fluoroscopie", "RATAEN": "Fluoroscopie", "RATASIRT": "Fluoroscopie", "RATATUBE": "Fluoroscopie",
    "RATBREV": "Fluoroscopie", "RATBTUBE": "Fluoroscopie", "RATKHTUBE": "Fluoroscopie",
    "RATNAOEN@": "Fluoroscopie", "RATNIGUIDE": "Fluoroscopie", "RATNREV": "Fluoroscopie",
    "RATNTUBE@": "Fluoroscopie", "RATOEPICC": "Fluoroscopie", "RATOETUBE": "Fluoroscopie",
    "RATTEN": "Fluoroscopie", "RATTTUBE": "Fluoroscopie", "RATUETUBE": "Fluoroscopie",
    "RATWSTUBE": "Fluoroscopie", "RBDMLOKBDS": "Fluoroscopie", "RBDMLOKL": "Fluoroscopie",
    "RBDMLOKR": "Fluoroscopie", "RBDMMIL": "Fluoroscopie", "RBDMMIR": "Fluoroscopie",
    "RBDMSTBLL": "Fluoroscopie", "RBDMSTBLR": "Fluoroscopie", "RBDMVMIL": "Fluoroscopie",
    "RBDMVMIR": "Fluoroscopie", "RBEMAM": "Roentgen", "RBNMB": "Roentgen", "RBNMBKOMBI": "Roentgen",
    "RBNMJODB": "Roentgen", "RBNMJODL": "Roentgen", "RBNMJODR": "Roentgen", "RBNMKOMBI@": "Roentgen",
    "RBNML": "Roentgen", "RBNMLKOMBI": "Roentgen", "RBNMLOKL": "Roentgen", "RBNMLOKR": "Roentgen",
    "RBNMPB": "Roentgen", "RBNMPRAEL": "Roentgen", "RBNMPRAER": "Roentgen", "RBNMR": "Roentgen",
    "RBNMRKOMBI": "Roentgen", "RBNMSCRE": "Roentgen", "RBNMSCZB": "Roentgen", "RBNMSPL": "Roentgen",
    "RBNMSPR": "Roentgen", "RCAAB": "CT", "RCAABB": "CT", "RCAHA": "CT", "RCAK": "CT", "RCAOBDS": "CT",
    "RCAOL": "CT", "RCAOR": "CT", "RCAR": "CT", "RCAS": "CT", "RCATH": "CT", "RCATHAB": "CT", "RCAUBDS": "CT",
    "RCAUL": "CT", "RCAUR": "CT", "RCAWS": "CT", "RCDN": "CT", "RCEA": "CT", "RCEBE": "CT", "RCECT": "CT",
    "RCEHA": "CT", "RCEK": "CT", "RCEKHWS": "CT", "RCEKNNH": "CT", "RCEN": "CT", "RCENHAKANG": "CT",
    "RCENHAT": "CT", "RCENHATA": "CT", "RCENTA": "CT", "RCENTAANG": "CT", "RCEO": "CT", "RCER": "CT",
    "RCET": "CT", "RCETHIPF": "CT", "RCEU": "CT", "RCEW": "CT", "RCNA@": "CT", "RCNAB": "CT", "RCNABB": "CT",
    "RCNAOB": "CT", "RCNBE": "CT", "RCNBEART": "CT", "RCNC@": "CT", "RCNCAO": "CT", "RCNCLIV": "CT",
    "RCNCO": "CT", "RCNCOR": "CT", "RCNCTHA": "CT", "RCNG": "CT", "RCNHA": "CT", "RCNK": "CT", "RCNKG@": "CT",
    "RCNKGDEN": "CT", "RCNKGE": "CT", "RCNKGEN": "CT", "RCNKGEUK": "CT", "RCNKGO": "CT", "RCNKGOK": "CT",
    "RCNKGOKUK": "CT", "RCNKGUK": "CT", "RCNKHT": "CT", "RCNKM": "CT", "RCNKR": "CT", "RCNKS@": "CT",
    "RCNKSBAS": "CT", "RCNKSCH": "CT", "RCNKSCHHWS": "CT", "RCNN": "CT", "RCNNK": "CT", "RCNNKHT": "CT",
    "RCNNRADONK": "CT", "RCNNUARTHH": "CT", "RCNOARTHGL": "CT", "RCNOARTHGR": "CT", "RCNOARTHL": "CT",
    "RCNOARTHR": "CT", "RCNOARTHSL": "CT", "RCNOARTHSR": "CT", "RCNOBDS": "CT", "RCNOCLBDS": "CT",
    "RCNOELL": "CT", "RCNOELR": "CT", "RCNOHABDS": "CT", "RCNOHAL": "CT", "RCNOHAR": "CT", "RCNOHGBDS": "CT",
    "RCNOHGL": "CT", "RCNOHGR": "CT", "RCNOL": "CT", "RCNOOBL": "CT", "RCNOOBR": "CT", "RCNOR": "CT",
    "RCNOSC": "CT", "RCNOSCHBDS": "CT", "RCNOSCHL": "CT", "RCNOSCHR": "CT", "RCNOUNBDS": "CT", "RCNOUNL": "CT",
    "RCNOUNR": "CT", "RCNR": "CT", "RCNR@": "CT", "RCNRTHA": "CT", "RCNRTHAB": "CT", "RCNT@": "CT",
    "RCNTH": "CT", "RCNTHH": "CT", "RCNTHO": "CT", "RCNUARTHHL": "CT", "RCNUARTHHR": "CT", "RCNUARTHKL": "CT",
    "RCNUARTHKR": "CT", "RCNUARTHL": "CT", "RCNUARTHOL": "CT", "RCNUARTHOR": "CT", "RCNUARTHR": "CT",
    "RCNUBDS": "CT", "RCNUFUBDS": "CT", "RCNUFUL": "CT", "RCNUFUR": "CT", "RCNUHUL": "CT", "RCNUHUR": "CT",
    "RCNUKNBDS": "CT", "RCNUKNL": "CT", "RCNUKNR": "CT", "RCNUL": "CT", "RCNUOBBDS": "CT", "RCNUOBL": "CT",
    "RCNUOBR": "CT", "RCNUOSGBDS": "CT", "RCNUOSGL": "CT", "RCNUOSGR": "CT", "RCNUR": "CT", "RCNUUNBDS": "CT",
    "RCNUUNL": "CT", "RCNUUNR": "CT", "RCNWS": "CT", "RCNWSB": "CT", "RCNWSH": "CT", "RCNWSL": "CT",
    "RCNWSLBE": "CT", "RCON": "CT", "RCOW": "CT", "RCTN": "CT", "RDDN": "Fluoroscopie",
    "RDEABD": "Fluoroscopie", "RDEH": "Fluoroscopie", "RDEK": "Fluoroscopie", "RDENNFS": "Fluoroscopie",
    "RDEO": "Fluoroscopie", "RDETH": "Fluoroscopie", "RDEU": "Fluoroscopie", "RDEW": "Fluoroscopie",
    "RDNA": "Fluoroscopie", "RDNBETL": "Fluoroscopie", "RDNBETR": "Fluoroscopie", "RDNH": "Fluoroscopie",
    "RDNK": "Fluoroscopie", "RDNKKIE": "Fluoroscopie", "RDNKNNH": "Fluoroscopie", "RDNNFK": "Fluoroscopie",
    "RDNOCLAL": "Fluoroscopie", "RDNOCLAR": "Fluoroscopie", "RDNOEGL": "Fluoroscopie",
    "RDNOEGR": "Fluoroscopie", "RDNOFIL": "Fluoroscopie", "RDNOFIR": "Fluoroscopie", "RDNOHAL": "Fluoroscopie",
    "RDNOHAR": "Fluoroscopie", "RDNOHGBDS": "Fluoroscopie", "RDNOHGL": "Fluoroscopie",
    "RDNOHGR": "Fluoroscopie", "RDNOOAL": "Fluoroscopie", "RDNOOAR": "Fluoroscopie",
    "RDNOSGBDS": "Fluoroscopie", "RDNOSGL": "Fluoroscopie", "RDNOSGR": "Fluoroscopie",
    "RDNOUAL": "Fluoroscopie", "RDNOUAR": "Fluoroscopie", "RDNTHL": "Fluoroscopie", "RDNTHLI": "Fluoroscopie",
    "RDNTHR": "Fluoroscopie", "RDNTHST": "Fluoroscopie", "RDNTRIL": "Fluoroscopie", "RDNTRIR": "Fluoroscopie",
    "RDNTST": "Fluoroscopie", "RDNUCAL": "Fluoroscopie", "RDNUCAR": "Fluoroscopie", "RDNUFUBDS": "Fluoroscopie",
    "RDNUFUL": "Fluoroscopie", "RDNUFUR": "Fluoroscopie", "RDNUHUL": "Fluoroscopie", "RDNUHUR": "Fluoroscopie",
    "RDNUKNL": "Fluoroscopie", "RDNUKNR": "Fluoroscopie", "RDNUMFL": "Fluoroscopie", "RDNUMFR": "Fluoroscopie",
    "RDNUOSBDS": "Fluoroscopie", "RDNUOSGBDS": "Fluoroscopie", "RDNUOSGL": "Fluoroscopie",
    "RDNUOSGR": "Fluoroscopie", "RDNUOSL": "Fluoroscopie", "RDNUOSR": "Fluoroscopie",
    "RDNUUOSBDS": "Fluoroscopie", "RDNUUSBDS": "Fluoroscopie", "RDNUUSL": "Fluoroscopie",
    "RDNUUSR": "Fluoroscopie", "RDNUVFR": "Fluoroscopie", "RDNUVRL": "Fluoroscopie", "RDNWBWSL": "Fluoroscopie",
    "RDNWHWSL": "Fluoroscopie", "RDNWLP": "Fluoroscopie", "RDNWLWSL": "Fluoroscopie", "RDONOP": "Fluoroscopie",
    "RDTN": "Fluoroscopie", "RKDNINF": "Fluoroscopie", "RKNAANTURO": "Fluoroscopie",
    "RKNAANUBDS": "Fluoroscopie", "RKNAANUREL": "Fluoroscopie", "RKNAANURER": "Fluoroscopie",
    "RKNAAUG": "Fluoroscopie", "RKNACAVE": "Fluoroscopie", "RKNACHOLT": "Fluoroscopie",
    "RKNACOL": "Fluoroscopie", "RKNADEF": "Fluoroscopie", "RKNADIFFSP": "Fluoroscopie",
    "RKNADJB": "Fluoroscopie", "RKNADJL": "Fluoroscopie", "RKNADJR": "Fluoroscopie", "RKNAERCP": "Fluoroscopie",
    "RKNAGENI": "Fluoroscopie", "RKNAHSG": "Fluoroscopie", "RKNAMCU": "Fluoroscopie", "RKNAMDP": "Fluoroscopie",
    "RKNANEPHL": "Fluoroscopie", "RKNANEPHR": "Fluoroscopie", "RKNAOEMDP": "Fluoroscopie",
    "RKNAOESO": "Fluoroscopie", "RKNAREKSTU": "Fluoroscopie", "RKNARETURO": "Fluoroscopie",
    "RKNAREUREB": "Fluoroscopie", "RKNAREUREL": "Fluoroscopie", "RKNAREURER": "Fluoroscopie",
    "RKNASELDD": "Fluoroscopie", "RKNAVESB": "Fluoroscopie", "RKNAVESL": "Fluoroscopie",
    "RKNAVESR": "Fluoroscopie", "RKNAZYST": "Fluoroscopie", "RKNBURODY": "Fluoroscopie",
    "RKNKCYS": "Fluoroscopie", "RKNKDAKB": "Fluoroscopie", "RKNKDAKL": "Fluoroscopie",
    "RKNKDAKR": "Fluoroscopie", "RKNKKGAL": "Fluoroscopie", "RKNKKGAR": "Fluoroscopie",
    "RKNKPUD": "Fluoroscopie", "RKNKSIAL": "Fluoroscopie", "RKNKSIAR": "Fluoroscopie",
    "RKNKVEN": "Fluoroscopie", "RKNMGALL": "Fluoroscopie", "RKNMGALR": "Fluoroscopie",
    "RKNNFISHOE": "Fluoroscopie", "RKNNKATKO": "Fluoroscopie", "RKNNKATREV": "Fluoroscopie",
    "RKNOACAL": "Roentgen", "RKNOACAR": "Roentgen", "RKNOEGAL": "Roentgen", "RKNOEGAR": "Roentgen",
    "RKNOFGAL": "Roentgen", "RKNOFGAR": "Roentgen", "RKNOHGAL": "Roentgen", "RKNOHGAR": "Roentgen",
    "RKNOSGAL": "Roentgen", "RKNOSGAR": "Roentgen", "RKNOSTAL": "Roentgen", "RKNOSTAR": "Roentgen",
    "RKNUHUAL": "Roentgen", "RKNUHUAR": "Roentgen", "RKNUKNAL": "Roentgen", "RKNUKNAR": "Roentgen",
    "RKNUOSGAL": "Roentgen", "RKNUOSGAR": "Roentgen", "RKNUUSGAL": "Roentgen", "RKNUUSGAR": "Roentgen",
    "RKNUZEAL": "Roentgen", "RKNUZEAR": "Roentgen", "RKNWIVGCA": "Roentgen", "RKNWIVGLA": "Roentgen",
    "RKNWIVGTA": "Roentgen", "RKNWMYEC": "Fluoroscopie", "RKNWMYEL": "Fluoroscopie", "RKNWMYET": "Fluoroscopie",
    "RKTNINF": "Fluoroscopie", "RKTNRASYN": "Fluoroscopie", "RKTWRFNC": "Fluoroscopie",
    "RKTWRFNL": "Fluoroscopie", "RKTWRFNT": "Fluoroscopie", "RMAA": "MRI", "RMAB": "MRI", "RMABB": "MRI",
    "RMABK": "MRI", "RMAK": "MRI", "RMAKANGIO": "MRI", "RMAKH": "MRI", "RMAKHANGIO": "MRI", "RMAN": "MRI",
    "RMAUB": "MRI", "RMAUFB": "MRI", "RMAUFL": "MRI", "RMAUFR": "MRI", "RMAUL": "MRI", "RMAUR": "MRI",
    "RMAW": "MRI", "RMAXAORTA": "MRI", "RMAXCAROT": "MRI", "RMDKNOPUN": "MRI", "RMDMBDS": "MRI", "RMDML": "MRI",
    "RMDMLOBDS": "MRI", "RMDMLOL": "MRI", "RMDMLOR": "MRI", "RMDMR": "MRI", "RMDN": "MRI", "RMDORG": "MRI",
    "RMEA": "MRI", "RMEBE": "MRI", "RMEGK": "MRI", "RMEH": "MRI", "RMEK": "MRI", "RMEMAM": "MRI",
    "RMEMRI": "MRI", "RMENHAT": "MRI", "RMEO": "MRI", "RMER": "MRI", "RMET": "MRI", "RMEU": "MRI",
    "RMEW": "MRI", "RMNA": "MRI", "RMNAB": "MRI", "RMNB": "MRI", "RMNBFE": "MRI", "RMNBK": "MRI", "RMNC": "MRI",
    "RMNCBELA": "MRI", "RMNGK": "MRI", "RMNGKK": "MRI", "RMNH": "MRI", "RMNHK": "MRI", "RMNK": "MRI",
    "RMNKGS": "MRI", "RMNKHY": "MRI", "RMNKK": "MRI", "RMNKKG": "MRI", "RMNKOHNANG": "MRI", "RMNM": "MRI",
    "RMNNM": "MRI", "RMNNMOE": "MRI", "RMNNMSP": "MRI", "RMNNMUE": "MRI", "RMNO": "MRI", "RMNOANGL": "MRI",
    "RMNOANGR": "MRI", "RMNOARTHEL": "MRI", "RMNOARTHER": "MRI", "RMNOARTHGL": "MRI", "RMNOARTHGR": "MRI",
    "RMNOARTHHL": "MRI", "RMNOARTHHR": "MRI", "RMNOARTHSL": "MRI", "RMNOARTHSR": "MRI", "RMNOB": "MRI",
    "RMNOELL": "MRI", "RMNOELLK": "MRI", "RMNOELR": "MRI", "RMNOELRK": "MRI", "RMNOFIL": "MRI",
    "RMNOFIR": "MRI", "RMNOHAB": "MRI", "RMNOHAL": "MRI", "RMNOHAR": "MRI", "RMNOHGB": "MRI", "RMNOHGL": "MRI",
    "RMNOHGR": "MRI", "RMNOL": "MRI", "RMNOOAL": "MRI", "RMNOOAR": "MRI", "RMNOR": "MRI", "RMNOSCHL": "MRI",
    "RMNOSCHR": "MRI", "RMNOUAL": "MRI", "RMNOUAR": "MRI", "RMNT": "MRI", "RMNTHA": "MRI", "RMNUAB": "MRI",
    "RMNUAL": "MRI", "RMNUAR": "MRI", "RMNUARTHHL": "MRI", "RMNUARTHHR": "MRI", "RMNUARTHKL": "MRI",
    "RMNUARTHKR": "MRI", "RMNUARTHOL": "MRI", "RMNUARTHOR": "MRI", "RMNUB": "MRI", "RMNUFL": "MRI",
    "RMNUFR": "MRI", "RMNUHB": "MRI", "RMNUHL": "MRI", "RMNUHLK": "MRI", "RMNUHR": "MRI", "RMNUHRK": "MRI",
    "RMNUKB": "MRI", "RMNUKL": "MRI", "RMNUKR": "MRI", "RMNUL": "MRI", "RMNUOSB": "MRI", "RMNUOSL": "MRI",
    "RMNUOSR": "MRI", "RMNUR": "MRI", "RMNUROT": "MRI", "RMNUSPL": "MRI", "RMNUSPR": "MRI", "RMNUUSB": "MRI",
    "RMNUUSL": "MRI", "RMNUUSR": "MRI", "RMNWSB": "MRI", "RMNWSBE": "MRI", "RMNWSG": "MRI", "RMNWSH": "MRI",
    "RMNWSL": "MRI", "RMNWSPB": "MRI", "RMNWSPL": "MRI", "RMNWSS": "MRI", "RMTN": "MRI", "RMTNRFA": "MRI",
    "RMYNINTERV": "MRI", "RPDABECK": "Fluoroscopie", "RPDK": "Fluoroscopie", "RPDNCAV": "Fluoroscopie",
    "RPDOE": "Fluoroscopie", "RPDUE": "Fluoroscopie", "RPYNPHLEB": "Fluoroscopie", "RREA": "Roentgen",
    "RRNA": "Roentgen", "RRNAHEL": "Roentgen", "RRNAHER": "Roentgen", "RRNAL": "Roentgen",
    "RRNBEDL": "Roentgen", "RRNBETL@": "Roentgen", "RRNBETR@": "Roentgen", "RRNHTR": "Roentgen",
    "RRNK@": "Roentgen", "RRNKKIE@": "Roentgen", "RRNKNNH@": "Roentgen", "RRNMB": "Roentgen",
    "RRNML": "Roentgen", "RRNMLOKL": "Roentgen", "RRNMLOKR": "Roentgen", "RRNMPRAEL": "Roentgen",
    "RRNMPRAER": "Roentgen", "RRNMR": "Roentgen", "RRNMSCZB": "Roentgen", "RRNMSPL": "Roentgen",
    "RRNMSPR": "Roentgen", "RRNOCLAL@": "Roentgen", "RRNOCLAR@": "Roentgen", "RRNOEDL": "Roentgen",
    "RRNOEGL@": "Roentgen", "RRNOEGR@": "Roentgen", "RRNOFIL@": "Roentgen", "RRNOFIR@": "Roentgen",
    "RRNOHAL@": "Roentgen", "RRNOHAR@": "Roentgen", "RRNOHGL@": "Roentgen", "RRNOHGR@": "Roentgen",
    "RRNOOAL@": "Roentgen", "RRNOOAR@": "Roentgen", "RRNOSGL@": "Roentgen", "RRNOSGR@": "Roentgen",
    "RRNOUAL@": "Roentgen", "RRNOUAR@": "Roentgen", "RRNRKISTA": "Roentgen", "RRNTHJOD": "Roentgen",
    "RRNTHLI": "Roentgen", "RRNTHLI@": "Roentgen", "RRNTHLIN": "Roentgen", "RRNTHSI": "Roentgen",
    "RRNTHST": "Roentgen", "RRNTHST@": "Roentgen", "RRNTHTEI": "Roentgen", "RRNTKI": "Roentgen",
    "RRNTRIL@": "Roentgen", "RRNTRIR@": "Roentgen", "RRNUCAL@": "Roentgen", "RRNUCAR@": "Roentgen",
    "RRNUEDL": "Roentgen", "RRNUFUL@": "Roentgen", "RRNUFUR@": "Roentgen", "RRNUHUL@": "Roentgen",
    "RRNUHUR@": "Roentgen", "RRNUKNL@": "Roentgen", "RRNUKNR@": "Roentgen", "RRNUMFL@": "Roentgen",
    "RRNUMFR@": "Roentgen", "RRNUOSGL@": "Roentgen", "RRNUOSGR@": "Roentgen", "RRNUOSL@": "Roentgen",
    "RRNUOSR@": "Roentgen", "RRNUUSL@": "Roentgen", "RRNUUSR@": "Roentgen", "RRNUVFL@": "Roentgen",
    "RRNUVFR@": "Roentgen", "RRNWBWSL@": "Roentgen", "RRNWHWSL@": "Roentgen", "RRNWLWSL@": "Roentgen",
    "RSEBE": "Roentgen", "RSEDEXA": "Roentgen", "RSEK": "Roentgen", "RSEKDVT": "Roentgen", "RSEO": "Roentgen",
    "RSETH": "Roentgen", "RSEU": "Roentgen", "RSEW": "Roentgen", "RSNBEDUNN": "Roentgen",
    "RSNBEHBDS": "Roentgen", "RSNBEHL": "Roentgen", "RSNBEHR": "Roentgen", "RSNBELI": "Roentgen",
    "RSNBEST": "Roentgen", "RSNBETL": "Roentgen", "RSNBETR": "Roentgen", "RSNBISG": "Roentgen",
    "RSNBSA": "Roentgen", "RSNBST": "Roentgen", "RSNDMRB": "Roentgen", "RSNDORB": "Roentgen",
    "RSNGRGK": "Roentgen", "RSNGSSTAT": "Roentgen", "RSNK": "Roentgen", "RSNKJO": "Roentgen",
    "RSNKKIE": "Roentgen", "RSNKKIL": "Roentgen", "RSNKKIR": "Roentgen", "RSNKNAB": "Roentgen",
    "RSNKNNH": "Roentgen", "RSNKOPG": "Roentgen", "RSNKOR": "Roentgen", "RSNKZAHN": "Roentgen",
    "RSNNFK": "Roentgen", "RSNNGSHAE": "Roentgen", "RSNNKON": "Roentgen", "RSNOACGL": "Roentgen",
    "RSNOACGPA": "Roentgen", "RSNOACGPAB": "Roentgen", "RSNOACGR": "Roentgen", "RSNOCLAL": "Roentgen",
    "RSNOCLAR": "Roentgen", "RSNOEGBDS": "Roentgen", "RSNOEGL": "Roentgen", "RSNOEGNOL": "Roentgen",
    "RSNOEGNOR": "Roentgen", "RSNOEGR": "Roentgen", "RSNOEG3DLI": "Roentgen", "RSNOEG3DRE": "Roentgen",
    "RSNOFIL": "Roentgen", "RSNOFIR": "Roentgen", "RSNOHAA": "Roentgen", "RSNOHAB": "Roentgen",
    "RSNOHABDS": "Roentgen", "RSNOHACAL": "Roentgen", "RSNOHACAR": "Roentgen", "RSNOHAL": "Roentgen",
    "RSNOHAR": "Roentgen", "RSNOHAWUL": "Roentgen", "RSNOHAWUR": "Roentgen", "RSNOHGBDS": "Roentgen",
    "RSNOHGL": "Roentgen", "RSNOHGR": "Roentgen", "RSNOHG3DLI": "Roentgen", "RSNOHG3DRE": "Roentgen",
    "RSNOOABDS": "Roentgen", "RSNOOAL": "Roentgen", "RSNOOAR": "Roentgen", "RSNOOSCL": "Roentgen",
    "RSNOOSCR": "Roentgen", "RSNORKNOL": "Roentgen", "RSNORKNOR": "Roentgen", "RSNOSCL": "Roentgen",
    "RSNOSCR": "Roentgen", "RSNOSGBDS": "Roentgen", "RSNOSGL": "Roentgen", "RSNOSGR": "Roentgen",
    "RSNOSGSCL": "Roentgen", "RSNOSGSCR": "Roentgen", "RSNOSG3DLI": "Roentgen", "RSNOSG3DRE": "Roentgen",
    "RSNOUAL": "Roentgen", "RSNOUAR": "Roentgen", "RSNTRIL": "Roentgen", "RSNTRIR": "Roentgen",
    "RSNTST": "Roentgen", "RSNTST@": "Roentgen", "RSNTSTCGL": "Roentgen", "RSNTSTCGR": "Roentgen",
    "RSNUCABDS": "Roentgen", "RSNUCAL": "Roentgen", "RSNUCAR": "Roentgen", "RSNUFO3DBD": "Roentgen",
    "RSNUFO3DLI": "Roentgen", "RSNUFO3DRE": "Roentgen", "RSNUFUBDS": "Roentgen", "RSNUFUL": "Roentgen",
    "RSNUFUR": "Roentgen", "RSNUFUSB": "Roentgen", "RSNUFUSL": "Roentgen", "RSNUFUSR": "Roentgen",
    "RSNUGBL": "Roentgen", "RSNUGBR": "Roentgen", "RSNUHUL": "Roentgen", "RSNUHUR": "Roentgen",
    "RSNUHU3DLI": "Roentgen", "RSNUHU3DRE": "Roentgen", "RSNUKGEA": "Roentgen", "RSNUKNBDS": "Roentgen",
    "RSNUKNL": "Roentgen", "RSNUKNPBDS": "Roentgen", "RSNUKNPL": "Roentgen", "RSNUKNPR": "Roentgen",
    "RSNUKNR": "Roentgen", "RSNUKNSTL": "Roentgen", "RSNUKNSTR": "Roentgen", "RSNUKN3DLI": "Roentgen",
    "RSNUKN3DRE": "Roentgen", "RSNUMFL": "Roentgen", "RSNUMFR": "Roentgen", "RSNUORT": "Roentgen",
    "RSNUOSBDS": "Roentgen", "RSNUOSGBDS": "Roentgen", "RSNUOSGL": "Roentgen", "RSNUOSGR": "Roentgen",
    "RSNUOSGSAB": "Roentgen", "RSNUOSGSAL": "Roentgen", "RSNUOSGSAR": "Roentgen", "RSNUOSGSL": "Roentgen",
    "RSNUOSGSR": "Roentgen", "RSNUOSL": "Roentgen", "RSNUOSR": "Roentgen", "RSNUPAB": "Roentgen",
    "RSNUPABDS": "Roentgen", "RSNUPAL": "Roentgen", "RSNUPAR": "Roentgen", "RSNUUSBDS": "Roentgen",
    "RSNUUSL": "Roentgen", "RSNUUSR": "Roentgen", "RSNUVFL": "Roentgen", "RSNUVFR": "Roentgen",
    "RSNUZEL": "Roentgen", "RSNUZER": "Roentgen", "RSNWBWSAL": "Roentgen", "RSNWBWSBFU": "Roentgen",
    "RSNWBWSFU": "Roentgen", "RSNWBWSL": "Roentgen", "RSNWBWSS": "Roentgen", "RSNWBWS3D": "Roentgen",
    "RSNWCETUL": "Roentgen", "RSNWCETUS": "Roentgen", "RSNWDENSL": "Roentgen", "RSNWDENSS": "Roentgen",
    "RSNWFUL": "Roentgen", "RSNWGWS": "Roentgen", "RSNWHWDL": "Roentgen", "RSNWHWDS": "Roentgen",
    "RSNWHWSALD": "Roentgen", "RSNWHWSFU": "Roentgen", "RSNWHWSHFU": "Roentgen", "RSNWHWSL": "Roentgen",
    "RSNWHWSS": "Roentgen", "RSNWHWS3D": "Roentgen", "RSNWLUSUL": "Roentgen", "RSNWLUSUS": "Roentgen",
    "RSNWLWSAL": "Roentgen", "RSNWLWSFU": "Roentgen", "RSNWLWSL": "Roentgen", "RSNWLWSLFU": "Roentgen",
    "RSNWLWSS": "Roentgen", "RSNWLWS3D": "Roentgen", "RSNWTHLUAL": "Roentgen", "RSNWTHLUL": "Roentgen",
    "RSNWTHLUS": "Roentgen", "RUD@": "Sonographie", "RUDA": "Sonographie", "RUDH": "Sonographie",
    "RUDM": "Sonographie", "RUDNOEL": "Sonographie", "RUDNUEL": "Sonographie", "RUDOEL": "Sonographie",
    "RUDOER": "Sonographie", "RUDR": "Sonographie", "RUDT": "Sonographie", "RUDUEL": "Sonographie",
    "RUDUER": "Sonographie", "RUEABD": "Sonographie", "RUEBE": "Sonographie", "RUECECHO": "Sonographie",
    "RUEHA": "Sonographie", "RUEMAM": "Sonographie", "RUEO": "Sonographie", "RUEU": "Sonographie",
    "RUNAB@": "Sonographie", "RUNABD": "Sonographie", "RUNABDD": "Sonographie", "RUNABDHO": "Sonographie",
    "RUNABDHOKM": "Sonographie", "RUNABDO": "Sonographie", "RUNABORG": "Sonographie", "RUNABOVA": "Sonographie",
    "RUNABRH": "Sonographie", "RUNABUBB": "Sonographie", "RUNABW": "Sonographie", "RUNAEND@": "Sonographie",
    "RUNAENDO": "Sonographie", "RUNAENDREC": "Sonographie", "RUNAENDRV": "Sonographie",
    "RUNAENDU": "Sonographie", "RUNAKM@": "Sonographie", "RUNAKMHEP": "Sonographie", "RUNAKMMI": "Sonographie",
    "RUNAKMNIBD": "Sonographie", "RUNAKMNIL": "Sonographie", "RUNAKMNIR": "Sonographie",
    "RUNAKMPAN": "Sonographie", "RUNALK": "Sonographie", "RUNAURO": "Sonographie", "RUNAUROL": "Sonographie",
    "RUNBINGL": "Sonographie", "RUNBINGR": "Sonographie", "RUNBLEIBDS": "Sonographie",
    "RUNBLEIL": "Sonographie", "RUNBLEIR": "Sonographie", "RUNCECANA": "Sonographie", "RUNCECHO": "Sonographie",
    "RUNCECMUP": "Sonographie", "RUNH@": "Sonographie", "RUNHESWLSS": "Sonographie", "RUNHHNO": "Sonographie",
    "RUNHLKL": "Sonographie", "RUNHLKR": "Sonographie", "RUNHSD": "Sonographie", "RUNHSDHNO": "Sonographie",
    "RUNHSDKM": "Sonographie", "RUNHSDS": "Sonographie", "RUNHSPDB": "Sonographie", "RUNHSPDL": "Sonographie",
    "RUNHSPDR": "Sonographie", "RUNHWTB": "Sonographie", "RUNHWTBS": "Sonographie", "RUNHWTL": "Sonographie",
    "RUNHWTR": "Sonographie", "RUNKTF": "Sonographie", "RUNKWT": "Sonographie", "RUNMAMB": "Sonographie",
    "RUNMAML": "Sonographie", "RUNMAML@": "Sonographie", "RUNMAMR": "Sonographie", "RUNMAMR@": "Sonographie",
    "RUNMPRAEP": "Sonographie", "RUNNEV": "Sonographie", "RUNNWT": "Sonographie", "RUNOHABDS": "Sonographie",
    "RUNOHAL": "Sonographie", "RUNOHAR": "Sonographie", "RUNOL@": "Sonographie", "RUNOLEGL": "Sonographie",
    "RUNOLHGL": "Sonographie", "RUNOLSGL": "Sonographie", "RUNOLWTL": "Sonographie", "RUNOR@": "Sonographie",
    "RUNOREGR": "Sonographie", "RUNORHGR": "Sonographie", "RUNORSGR": "Sonographie", "RUNORWTR": "Sonographie",
    "RUNOWTBDS": "Sonographie", "RUNRABDLK": "Sonographie", "RUNREFAST": "Sonographie", "RUNRLK": "Sonographie",
    "RUNRLK@": "Sonographie", "RUNRLKKM": "Sonographie", "RUNTBDS": "Sonographie", "RUNTH": "Sonographie",
    "RUNTL": "Sonographie", "RUNTLKL": "Sonographie", "RUNTLKR": "Sonographie", "RUNTR": "Sonographie",
    "RUNUBSHUEB": "Sonographie", "RUNUL@": "Sonographie", "RUNULACHSL": "Sonographie",
    "RUNULHUEL": "Sonographie", "RUNULKNL": "Sonographie", "RUNULSGFL": "Sonographie",
    "RUNULSHUEL": "Sonographie", "RUNULWTL": "Sonographie", "RUNUR@": "Sonographie",
    "RUNURACHSR": "Sonographie", "RUNURHUER": "Sonographie", "RUNURKNR": "Sonographie",
    "RUNURSGFR": "Sonographie", "RUNURSHUER": "Sonographie", "RUNURWTR": "Sonographie",
    "RUNUWTBDS": "Sonographie", "RUNWRM": "Sonographie", "RUON": "Sonographie", "RUON@": "Sonographie",
    "RUONANG": "Sonographie", "RUT": "Sonographie", "RUTM": "Sonographie", "RUTMAMLBIL": "Sonographie",
    "RUTMAMRBIR": "Sonographie", "RUTN": "Sonographie", "RUTNINF": "Sonographie", "RUTOEPICC": "Sonographie",
    "RUXVAB@": "Sonographie", "RUXVACAVI": "Sonographie", "RUXVAPORT": "Sonographie", "RUXVH@": "Sonographie",
    "RUXVHB": "Sonographie", "RUXVHL": "Sonographie", "RUXVHR": "Sonographie", "RUXVNKM": "Sonographie",
    "RUXVOEL": "Sonographie", "RUXVOEL@": "Sonographie", "RUXVOELTL": "Sonographie", "RUXVOER": "Sonographie",
    "RUXVOER@": "Sonographie", "RUXVOERTR": "Sonographie", "RUXVUEB": "Sonographie", "RUXVUEL": "Sonographie",
    "RUXVUER": "Sonographie", "RUXVUL": "Sonographie", "RUXVUL@": "Sonographie", "RUXVULKNL": "Sonographie",
    "RUXVULUSL": "Sonographie", "RUXVUR": "Sonographie", "RUXVUR@": "Sonographie", "RUXVURKNR": "Sonographie",
    "RUXVURUSR": "Sonographie", "RUXXA": "Sonographie", "RUXXA@": "Sonographie", "RUXXAAORTB": "Sonographie",
    "RUXXAAORTL": "Sonographie", "RUXXAAORTR": "Sonographie", "RUXXANIEL": "Sonographie",
    "RUXXANIER": "Sonographie", "RUXXANPEN": "Sonographie", "RUXXANTRAN": "Sonographie",
    "RUXXH@": "Sonographie", "RUXXHBRACH": "Sonographie", "RUXXHCARB": "Sonographie",
    "RUXXHCARL": "Sonographie", "RUXXHCARR": "Sonographie", "RUXXHSUBB": "Sonographie",
    "RUXXHSUBL": "Sonographie", "RUXXHSUBR": "Sonographie", "RUXXK@": "Sonographie", "RUXXKBASB": "Sonographie",
    "RUXXKBASL": "Sonographie", "RUXXKBASR": "Sonographie", "RUXXNKM": "Sonographie", "RUXXOL": "Sonographie",
    "RUXXOL@": "Sonographie", "RUXXOLSAXL": "Sonographie", "RUXXOR": "Sonographie", "RUXXOR@": "Sonographie",
    "RUXXORSAXR": "Sonographie", "RUXXUB": "Sonographie", "RUXXUL": "Sonographie", "RUXXUL@": "Sonographie",
    "RUXXULUSL": "Sonographie", "RUXXUR": "Sonographie", "RUXXUR@": "Sonographie", "RUXXURUSR": "Sonographie",
    "RXDC": "Fluoroscopie", "RXDCTEIL": "Fluoroscopie", "RXETC": "Fluoroscopie", "RXNCELEEXT": "Fluoroscopie",
    "RXTC": "Fluoroscopie", "RXTCALSEAB": "Fluoroscopie", "RXTCAORT": "Fluoroscopie",
    "RXTCCARI": "Fluoroscopie", "RXTCCMEMS": "Fluoroscopie", "RXTCCRT": "Fluoroscopie",
    "RXTCEPRFEA": "Fluoroscopie", "RXTCEPS": "Fluoroscopie", "RXTCEPSCRY": "Fluoroscopie",
    "RXTCEPSRFA": "Fluoroscopie", "RXTCF": "Fluoroscopie", "RXTCIMPE": "Fluoroscopie",
    "RXTCKLAP": "Fluoroscopie", "RXTCLEAK": "Fluoroscopie", "RXTCMIC": "Fluoroscopie",
    "RXTCPALYSE": "Fluoroscopie", "RXTCPERI": "Fluoroscopie", "RXTCPMICIM": "Fluoroscopie",
    "RXTCPMIHIS": "Fluoroscopie", "RXTCPMIHS": "Fluoroscopie", "RXTCPTCA": "Fluoroscopie",
    "RXTCREV": "Fluoroscopie", "RXTCSCHR": "Fluoroscopie", "RXTCSCORRE": "Fluoroscopie",
    "RXTCTAAO": "Fluoroscopie", "RXTCTAMI": "Fluoroscopie", "RXTCTFAO": "Fluoroscopie",
    "RXTCTKI": "Fluoroscopie", "RXTCTO": "Fluoroscopie", "RXTCV@": "Fluoroscopie", "RXTCVAL@": "Fluoroscopie",
    "RXTCVALM": "Fluoroscopie", "RXTCVALP": "Fluoroscopie", "RXTCVAS": "Fluoroscopie",
    "RXTCVHOVER": "Fluoroscopie", "RXTCVPF": "Fluoroscopie", "RYDALE@": "Fluoroscopie",
    "RYDALEB": "Fluoroscopie", "RYDAPTC": "Fluoroscopie", "RYDOEDIA": "Fluoroscopie", "RYDTPUL": "Fluoroscopie",
    "RYTAG@": "Fluoroscopie", "RYTAGNEU": "Fluoroscopie", "RYTAGWECH": "Fluoroscopie",
    "RYTALEBIO": "Fluoroscopie", "RYTANEPH": "Fluoroscopie", "RYTANEPHWE": "Fluoroscopie",
    "RYTATIP": "Fluoroscopie", "RYTNMAL": "Fluoroscopie", "RYTOEPICC": "Fluoroscopie",
    "RYTWVERT": "Fluoroscopie", "RZDWLUMBP": "Fluoroscopie", "XDGA": "Fluoroscopie", "XDGN": "Fluoroscopie",
    "XDGR": "Fluoroscopie", "XDKNOE": "Fluoroscopie", "XDKNOF": "Fluoroscopie", "XDKNOFM": "Fluoroscopie",
    "XDKNOHG": "Fluoroscopie", "XDKNOS": "Fluoroscopie", "XDKNOUA": "Fluoroscopie", "XDKNUZ": "Fluoroscopie",
    "XDKNUZM": "Fluoroscopie", "XDNOL": "Fluoroscopie", "XDNOR": "Fluoroscopie", "XDNUL": "Fluoroscopie",
    "XDNUR": "Fluoroscopie", "XDNW": "Fluoroscopie", "XDPHN": "Fluoroscopie", "XDPNT": "Fluoroscopie",
    "XDPNTB": "Fluoroscopie", "XDPNTBZ": "Fluoroscopie", "XDPNTEBUS": "Fluoroscopie", "XDPNTK": "Fluoroscopie",
    "XDPNTS": "Fluoroscopie", "XDSCW": "Fluoroscopie", "XDST": "Fluoroscopie", "XEEN": "Fluoroscopie",
    "XRKKAB": "Roentgen", "XRKKBF": "Roentgen", "XRKKDVT": "Roentgen", "XRKKEZ": "Roentgen",
    "XRKKFRS": "Roentgen", "XRKKOPG": "Roentgen", "XUCVABD": "Sonographie", "XUDVABD": "Sonographie",
    "XUKB": "Sonographie", "XUKK": "Sonographie", "XUKNA": "Sonographie", "XUKNAURO": "Sonographie",
    "XUKNNW": "Sonographie", "XUKNR": "Sonographie", "XUKNT": "Sonographie", "XUKOE": "Sonographie",
    "XUKRB": "Sonographie", "XUKRG": "Sonographie", "XUKW": "Sonographie", "XUMAB": "Sonographie",
    "XUMANKMB": "Sonographie", "XUMAOKM": "Sonographie", "XUMAURO": "Sonographie", "XUMSCHILD": "Sonographie",
    "XUNA": "Sonographie", "XUNAO": "Sonographie", "XUNAURO": "Sonographie", "XUNC": "Sonographie",
    "XUNNA": "Sonographie", "XUNNI": "Sonographie", "XUNNKM": "Sonographie", "XUNNW": "Sonographie",
    "XUNO": "Sonographie", "XUNR": "Sonographie", "XUNT": "Sonographie", "XUNU": "Sonographie",
    "XUPG": "Sonographie", "XURB": "Sonographie", "XURG": "Sonographie", "XURO": "Sonographie",
    "XUROE": "Sonographie", "XUROF": "Sonographie", "XUROH": "Sonographie", "XUROS": "Sonographie",
    "XURU": "Sonographie", "XURUA": "Sonographie", "XURUF": "Sonographie", "XURUK": "Sonographie",
    "XURUZ": "Sonographie", "XURW": "Sonographie", "XURWI": "Sonographie", "XURWSI": "Sonographie"
}

# subtext_to_dicom_modality_dict = {
#     'CT': 'CT',
#     '-CT': 'CT',
#     'CTA': 'CT',
#     'PET-CT': 'PT',
#     'PET/CT': 'PT',
#     'Mammografie': 'MG',
#     "Roentgen": 'CR',
#     u"Röntgen": 'CR',
#     'MRI-': 'MR',
#     'MRI': 'MR',
#     'MRT': 'MR',
#     'Szinti': 'NM',
#     'Sonografie': 'US',
#     'Sonographie': 'US',
# }


subtext_to_dicom_modality_dict = {
    'CT': 'CT',
    '-CT': 'CT',
    'CTA': 'CT',
    'computertomogaphie': 'CT',
    'Computertomogaphie': 'CT',
    'CTP': 'CT',

    'PET-CT': 'PT',
    'PET/CT': 'PT',
    'PET CT': 'PT',
    'PET': 'PT',

    'Mammografie': 'MG',

    'konventionellen Aufnahmen': 'CR',
    u'Röntgen Aufnahmen': 'CR',
    u'Röntgen-Aufnahmen': 'CR',
    u'Röntgen': 'CR',
    'Projektionsradiographien': 'CR',

    'MRI-': 'MR',
    'MRI': 'MR',
    'MRT': 'MR',
    'MRI-Aufnahmen': 'MR',
    'MR': 'MR',
    'magnetresonanztomopraphischen Aufnahmen': 'MR',
    'Magnetresonsanttomgraphie': 'MR',
    'Magnetresonsanttomgraphien': 'MR',

    'Szinti': 'NM',
    'Szinitgraphie': 'NM',
    'Szintigraphien': 'NM',

    'Sonografie': 'US',
    'Sonographie': 'US',
    'Ultraschalluntersuchung': 'US',
    'Ultraschall': 'US',
}
